# .github/workflows/ci.yml

on:
  pull_request:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jokes-mini:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using webhook
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      run: |
        curl -x POST "$deploy_url"
       












        # jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Deploy
#         # Only run this step if the branch is main
#         if: github.ref == 'refs/heads/main'
#         env:
#           deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
#         run: |
#           curl "$deploy_url"